2014-09-27 09:14:22,239 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-09-27 09:14:23,815 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2014-09-27 09:14:24,018 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-09-27 09:14:24,042 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-09-27 09:14:24,372 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-09-27 09:14:31,908 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, 'Argumento inv\xc3\xa1lido -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2014-09-27 09:14:31,909 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, 'Argumento inv\xc3\xa1lido -- BDB0054 illegal flag combination specified to DB_ENV->open')
2014-09-27 09:14:31,964 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
2014-09-27 09:14:38,742 - softwarecenter.db.pkginfo_impl.aptcache - ERROR - simulate failed
None
2014-09-27 09:14:38,746 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterRecommenderAPI', 'recommend_app', '{"pkgname": "sublime-text"}']'
2014-09-27 09:14:38,747 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:404: {'status': '404', 'content-length': '61', 'via': '1.1 sumac.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'HIT from sumac.canonical.com', 'age': '273', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"ac48fe5710ebda334744e2d913e7ba67"', 'cache-control': 'max-age=300', 'date': 'Sat, 27 Sep 2014 14:10:05 GMT', 'content-type': 'text/html; charset=utf-8', 'x-cache-lookup': 'HIT from sumac.canonical.com:3128'}
'
2014-09-27 09:14:38,747 - softwarecenter.db.categories - WARNING - Error while accessing the recommender service: WARNING:__main__:404: {'status': '404', 'content-length': '61', 'via': '1.1 sumac.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'HIT from sumac.canonical.com', 'age': '273', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"ac48fe5710ebda334744e2d913e7ba67"', 'cache-control': 'max-age=300', 'date': 'Sat, 27 Sep 2014 14:10:05 GMT', 'content-type': 'text/html; charset=utf-8', 'x-cache-lookup': 'HIT from sumac.canonical.com:3128'}

2014-09-27 09:14:38,747 - softwarecenter.ui.gtk3.widgets.recommendations - WARNING - Error while accessing the recommender agent: WARNING:__main__:404: {'status': '404', 'content-length': '61', 'via': '1.1 sumac.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'HIT from sumac.canonical.com', 'age': '273', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"ac48fe5710ebda334744e2d913e7ba67"', 'cache-control': 'max-age=300', 'date': 'Sat, 27 Sep 2014 14:10:05 GMT', 'content-type': 'text/html; charset=utf-8', 'x-cache-lookup': 'HIT from sumac.canonical.com:3128'}

2014-09-27 09:14:43,557 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-09-27 09:16:13,050 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-09-27 09:16:16,384 - softwarecenter.utils - WARNING - Could not determine the installed desktop file path for app-install desktop file: 'None'
2014-09-27 09:16:16,387 - softwarecenter.backend.zeitgeist_logger - WARNING - Invalid desktop file provided, impossible to log event
2014-09-27 12:28:29,816 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-09-27 12:28:35,002 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2014-09-27 12:28:35,776 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-09-27 12:28:35,810 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-09-27 12:28:36,279 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-09-27 12:28:37,733 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, 'Argumento inv\xc3\xa1lido -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2014-09-27 12:28:37,751 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, 'Argumento inv\xc3\xa1lido -- BDB0054 illegal flag combination specified to DB_ENV->open')
2014-09-27 12:28:58,939 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
2014-09-27 12:29:02,573 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-09-27 12:31:27,815 - softwarecenter.ui.gtk3.app - INFO - found a running software-center on dbus, reconnecting
2014-09-27 12:31:33,810 - softwarecenter.db.pkginfo_impl.aptcache - ERROR - simulate failed
None
2014-09-27 12:31:50,353 - softwarecenter.ui.gtk3.app - INFO - found a running software-center on dbus, reconnecting
2014-09-27 12:31:51,844 - softwarecenter.db.pkginfo_impl.aptcache - ERROR - simulate failed
None
2014-09-27 12:32:35,752 - softwarecenter.ui.gtk3.app - INFO - found a running software-center on dbus, reconnecting
2014-09-27 12:32:37,302 - softwarecenter.db.pkginfo_impl.aptcache - ERROR - simulate failed
None
2014-09-27 12:47:18,160 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-09-27 12:47:44,734 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-09-27 12:47:58,340 - softwarecenter.utils - WARNING - Could not determine the installed desktop file path for app-install desktop file: 'None'
2014-09-27 12:47:58,340 - softwarecenter.backend.zeitgeist_logger - WARNING - Invalid desktop file provided, impossible to log event
2014-10-12 17:30:49,300 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-10-12 17:30:53,449 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2014-10-12 17:30:54,177 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-10-12 17:30:54,207 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-10-12 17:30:54,371 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-10-12 17:31:07,080 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, 'Argumento inv\xc3\xa1lido -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2014-10-12 17:31:07,098 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, 'Argumento inv\xc3\xa1lido -- BDB0054 illegal flag combination specified to DB_ENV->open')
2014-10-12 17:31:09,909 - softwarecenter.db.pkginfo_impl.aptcache - ERROR - simulate failed
None
2014-10-12 17:31:10,344 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
2014-10-12 17:31:21,617 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2014-10-12 17:31:25,387 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-10-12 17:31:28,645 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterRecommenderAPI', 'recommend_app', '{"pkgname": "dropbox"}']'
2014-10-12 17:31:28,645 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2014-10-12 17:31:28,645 - softwarecenter.db.categories - WARNING - Error while accessing the recommender service: WARNING:__main__:no data

2014-10-12 17:31:28,646 - softwarecenter.ui.gtk3.widgets.recommendations - WARNING - Error while accessing the recommender agent: WARNING:__main__:no data

2014-10-12 17:34:21,727 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-10-12 17:34:28,071 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
